### PR TITLE
Update runtime

### PR DESCRIPTION
**Pull request by lionirdeadman**

### CODE REVIEW

**Comment by takluyver** [comment]
This doesn't seem to run on my system any more (neither this branch, nor the latest version). Fiddling with the permissions, it looks like it needs `--share=ipc` added (which [the docs](https://docs.flatpak.org/en/latest/sandbox-permissions.html) do say is necessary for X11 - not sure how it worked before).

**Comment by lionirdeadman** [comment]
Ah, it works for me on Wayland. That might've been how it ever worked. I'll add that.

**Comment by takluyver** [comment]
bot, build

:crossed_fingers:

**Comment by takluyver** [comment]
Thanks, that's working now. :slightly_smiling_face:

**Pull request merged**
